apiVersion: v1
kind: Pod
metadata:
  name: aerialist-master
  labels:
    {}
spec:
  volumes:
    - configMap:
        defaultMode: 420
        name: k8s-config
      name: vol-k8s-conf
  containers:
    - imagePullPolicy: Always
      name: init
      image: skhatiri/aerialist:k8s
      stdin: true
      stdinOnce: false
      # command:
        # - /bin/bash 
        # - -c 
        # - "$(COMMAND)"
      env:
        - name: COMMAND
          value: "python3 aerialist --help"
        - name: WEBDAV_HOST
          valueFrom:
            secretKeyRef:
              name: webdav
              key: host                     
        - name: WEBDAV_USER
          valueFrom:
            secretKeyRef:
              name: webdav
              key: user           
        - name: WEBDAV_PASS
          valueFrom:
            secretKeyRef:
              name: webdav
              key: pass         
      volumeMounts:
        - mountPath: /root/.kube/config
          name: vol-k8s-conf
          readOnly: true
          subPath: k8s-config.yaml
      tty: true
      resources:
        limits:
          cpu: 1000m
          memory: 2000Mi
        requests: {}
  affinity:
  initContainers:
  restartPolicy: Never  