apiVersion: batch/v1
kind: Job
metadata:
  name: batch-test
  labels:
    {}
spec:
  selector:
    matchLabels:
  template:
    metadata:
      labels:
        {}
    spec:
      volumes:
        - name: host-path-volume
          hostPath:
            path: VOLUME
      containers:
        - imagePullPolicy: Always
          name: container-0
          image: skhatiri/aerialist
          stdin: true
          stdinOnce: false
          command:
            - /bin/bash
            - -c
            - "$(COMMAND)" 
          tty: true
          env:
            - name: COMMAND
              value: "python3 aerialist --help"
          volumeMounts:
            - name: host-path-volume
              mountPath: /src/aerialist/results
          resources:
            requests:
              cpu: 750m
              memory: 300Mi
            limits:
              cpu: 750m
              memory: 300Mi
      affinity:
      imagePullSecrets:
        - name: dockerhub
      initContainers:
      restartPolicy: Never
  completions: 1
  suspend: false
  backoffLimit: 5
  completionMode: NonIndexed
  parallelism: 1
  ttlSecondsAfterFinished: 60
